/** @file
  Copyright (c) 2026, The Videre Project Authors. All rights reserved.
  SPDX-License-Identifier: Apache-2.0
**/

/* @generated by scripts/generate-db-types.mjs */
/* eslint-disable */
/* Source of truth: mtgo-db (Postgres). Do not edit by hand. */

export const FORMATS = [
  "Standard",
  "Modern",
  "Pioneer",
  "Vintage",
  "Legacy",
  "Pauper",
  "Premodern",
  "Extended",
  "Classic",
] as const;

export type FormatType = typeof FORMATS[number];

export const EVENTS = [
  "League",
  "Preliminary",
  "Challenge",
  "Showcase",
  "Qualifier",
  "Daily",
  "Premier",
  "Championship",
] as const;

export type EventType = typeof EVENTS[number];

export const RESULTS = [
  "win",
  "loss",
  "draw",
] as const;

export type ResultType = typeof RESULTS[number];

export const CARD_COLORS = [
  {
    symbol: "W",
    name: "WHITE",
    bit: 1,
  },
  {
    symbol: "U",
    name: "BLUE",
    bit: 2,
  },
  {
    symbol: "B",
    name: "BLACK",
    bit: 4,
  },
  {
    symbol: "R",
    name: "RED",
    bit: 8,
  },
  {
    symbol: "G",
    name: "GREEN",
    bit: 16,
  },
] as const;

export type CardColor = typeof CARD_COLORS[number];

export const CARD_TYPES = [
  "Artifact",
  "Creature",
  "Enchantment",
  "Instant",
  "Land",
  "Planeswalker",
  "Sorcery",
  "Battle",
  "Kindred",
] as const;

export type CardType = typeof CARD_TYPES[number];

export const CARD_RARITIES = [
  "basic land",
  "bonus",
  "common",
  "mythic",
  "promo",
  "rare",
  "token",
  "uncommon",
] as const;

export type CardRarity = typeof CARD_RARITIES[number];

export const CARD_RARITY_LADDER = [
  "common",
  "uncommon",
  "rare",
  "mythic",
] as const;

export type RankedCardRarity = typeof CARD_RARITY_LADDER[number];

export const CARD_RARITY_ALIASES = [
  {
    alias: "basic",
    rarity: "basic land",
  },
  {
    alias: "basicland",
    rarity: "basic land",
  },
  {
    alias: "land",
    rarity: "basic land",
  },
  {
    alias: "c",
    rarity: "common",
  },
  {
    alias: "m",
    rarity: "mythic",
  },
  {
    alias: "mythic rare",
    rarity: "mythic",
  },
  {
    alias: "mythicrare",
    rarity: "mythic",
  },
  {
    alias: "r",
    rarity: "rare",
  },
  {
    alias: "u",
    rarity: "uncommon",
  },
] as const;

export type CardRarityAlias = typeof CARD_RARITY_ALIASES[number];
