/** @file
  Copyright (c) 2026, The Videre Project Authors. All rights reserved.
  SPDX-License-Identifier: Apache-2.0
**/

/* @generated by scripts/generate-db-types.mjs */
/* eslint-disable */

import { defineSchema } from "@videreproject/sql-builder";
import type { EventType, FormatType, ResultType } from "@videreproject/constants";

export type RecordType = `${number}-${number}-${number}`;

export type CardQuantityPair = {
  id: number;
  name: string;
  quantity: number;
};

export type GameResult = {
  id: number;
  result: ResultType;
};

export const TABLE_COLUMNS = {
  "archetypes": [
    "id",
    "deck_id",
    "name",
    "archetype",
    "archetype_id",
    "provider",
  ],
  "card_catalog_variants": [
    "catalog_id",
    "card_id",
    "variant_type",
    "set_code",
    "name",
    "name_normalized",
    "card_texture_number",
    "is_foil",
    "is_token",
    "first_seen_at",
    "last_seen_at",
    "raw",
  ],
  "card_faces": [
    "card_id",
    "face_index",
    "source_catalog_id",
    "name",
    "name_normalized",
    "colors",
    "color_mask",
    "mana_value",
    "flavor_text",
    "mana_cost",
    "type_line",
    "oracle_text",
    "supertypes",
    "card_types",
    "subtypes",
    "power",
    "toughness",
    "loyalty",
    "defense",
    "artist",
    "art_id",
    "raw",
    "card_type_mask",
    "printed_name",
    "printed_name_normalized",
    "search_vector",
  ],
  "card_legalities": [
    "oracle_id",
    "format_code",
    "status",
    "source_rule_set_id",
    "first_seen_at",
    "last_seen_at",
  ],
  "cards": [
    "id",
    "oracle_id",
    "set_code",
    "collector_number",
    "name",
    "name_normalized",
    "art_id",
    "artist",
    "card_texture_number",
    "other_face_texture_number",
    "split_card_ids",
    "split_parent_card_id",
    "split_other_card_id",
    "colors",
    "color_identity",
    "color_mask",
    "color_identity_mask",
    "mana_value",
    "flavor_text",
    "mana_cost",
    "type_line",
    "oracle_text",
    "supertypes",
    "card_types",
    "subtypes",
    "power",
    "toughness",
    "loyalty",
    "defense",
    "rarity",
    "frame_style",
    "promo_label",
    "has_activated_ability",
    "should_work",
    "is_foil",
    "is_token",
    "first_seen_at",
    "last_seen_at",
    "raw",
    "card_type_mask",
    "printed_name",
    "printed_name_normalized",
    "search_vector",
  ],
  "catalog_items": [
    "catalog_id",
    "kind",
    "first_seen_at",
    "last_seen_at",
  ],
  "catalog_price_definitions": [
    "source",
    "catalog_id",
    "source_name",
    "source_cardset",
    "source_rarity",
    "source_version",
    "source_foil",
    "first_seen_at",
    "last_seen_at",
    "raw",
  ],
  "catalog_price_history": [
    "source",
    "price_date",
    "catalog_id",
    "sell_price",
    "first_seen_at",
    "last_seen_at",
  ],
  "decks": [
    "id",
    "event_id",
    "player",
    "mainboard",
    "sideboard",
  ],
  "events": [
    "id",
    "name",
    "date",
    "format",
    "kind",
    "rounds",
    "players",
  ],
  "formats": [
    "code",
    "name",
    "display_order",
  ],
  "matches": [
    "id",
    "event_id",
    "round",
    "player",
    "opponent",
    "record",
    "result",
    "isbye",
    "games",
  ],
  "oracle_cards": [
    "id",
    "name",
    "name_normalized",
    "mana_cost",
    "mana_value",
    "type_line",
    "oracle_text",
    "colors",
    "color_identity",
    "color_mask",
    "color_identity_mask",
    "supertypes",
    "card_types",
    "subtypes",
    "power",
    "toughness",
    "loyalty",
    "defense",
    "is_token",
    "first_seen_at",
    "last_seen_at",
    "search_vector",
    "card_type_mask",
  ],
  "pending_image_sync": [
    "catalog_id",
    "reason",
    "first_seen_at",
    "last_seen_at",
  ],
  "players": [
    "id",
    "name",
  ],
  "products": [
    "id",
    "set_code",
    "name",
    "name_normalized",
    "object_type",
    "texture_number",
    "is_tradable",
    "first_seen_at",
    "last_seen_at",
    "raw",
    "description",
    "search_vector",
  ],
  "sets": [
    "code",
    "name",
    "release_date",
    "age",
    "set_type",
    "first_seen_at",
    "last_seen_at",
    "raw",
  ],
  "standings": [
    "event_id",
    "rank",
    "player",
    "record",
    "points",
    "omwp",
    "gwp",
    "owp",
  ],
} as const;

export type TableName = keyof typeof TABLE_COLUMNS;

export type TableColumn<T extends TableName> = typeof TABLE_COLUMNS[T][number];

export const DATABASE_SCHEMA = defineSchema(TABLE_COLUMNS);

export const table = DATABASE_SCHEMA.table;
